package(default_visibility = ["//visibility:public"])

cc_library(
  name = "runner",
  hdrs = ["runner.h"],
  deps = ["//core/framework:framework",
          "//core/lib:thread_pool",
          "//core/util:logging"],
)
