package(default_visibility = ["//visibility:public"])

cc_library(
  name = "commandline",
  hdrs = ["commandline.h"],
  srcs = ["commandline.cc"],
  deps = [":logging"],
)

cc_library(
  name = "logging",
  hdrs = ["logging.h"],
  srcs = ["logging.cc"],
)
